print ("")
print ("Olá, vamos calcular?")
print ("")
calc0 = str(input("Informe a primeira variável:"))
print ("")
calc1 = str(input("Informe a segunda variável:"))
print ("")
calc = float(calc0.replace(",", "."))
calc2 = float(calc1.replace(",", "."))
tipoop = ("+","-","*","/")
tipo = str(input("Para informar qual operação será realizada siga a legenda: \n \nPara Soma informe + \n\nPara Subtração informe -\n \nPara Multiplicação informe *\n \nPara Divisão informe /\n \n \nQual operação iremos realizar?"))
if tipo =="+":
    print("\n----------------------------------------------")
    print("\nO resultado da soma das variáveis é {:.2f}".format(calc+calc2))
    print("\n----------------------------------------------")
    print("\nObrigada por utilizar essa calculadora!")
elif tipo =="-":
    print("\n----------------------------------------------")
    print("\nO resultado da subtração das variáveis é {:.2f}".format(calc-calc2))
    print("\n----------------------------------------------")
    print("\nObrigada por utilizar essa calculadora!")
elif tipo =="*":
    print("\n----------------------------------------------")
    print("\nO resultado da multiplicação das variáveis é {:.2f}".format(calc*calc2))
    print("\n----------------------------------------------")
    print("\nObrigada por utilizar essa calculadora!")
elif tipo =="/":
    print("\n----------------------------------------------")
    print("\nO resultado da divisão das variáveis é {:.2f}".format(calc/calc2))
    print("\n----------------------------------------------")
    print("\nObrigada por utilizar essa calculadora!")
else:
        print("\n----------------------------------------------")
        print("\nO tipo de operação selecionado não é válido, por gentileza recomeçe utilizando as operações (+,-,* ou /).")
        print("\n----------------------------------------------")
        print("\nObrigada por utilizar essa calculadora!")
